import type { SimulationData, Analysis } from './llm';

export interface ReportData {
  hotspot: string;
  timestamp: number;
  data: SimulationData;
  matchedMarkets?: { question: string; yes_probability: number }[];
}

/**
 * Generate a Markdown-formatted analysis report.
 */
export function generateMarkdownReport(report: ReportData): string {
  const { hotspot, timestamp, data, matchedMarkets } = report;
  const time = new Date(timestamp).toLocaleString('zh-CN', {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit',
  });

  const lines: string[] = [];
  lines.push('# LiveBoard 分析报告');
  lines.push('');
  lines.push(`**事件:** ${hotspot}`);
  lines.push(`**分析时间:** ${time}`);
  lines.push('');

  // Transmission chain
  const hotspots = data.nodes.filter(n => n.type === 'hotspot').map(n => n.label);
  const variables = data.nodes.filter(n => n.type === 'variable').map(n => n.label);
  const impacts = data.nodes.filter(n => n.type === 'impact').map(n => n.label);
  const assets = data.nodes.filter(n => n.type === 'asset').map(n => n.label);

  lines.push('## 传导链');
  lines.push('');
  lines.push(
    `${hotspots.join(', ') || '-'} → ${variables.join(', ') || '-'} → ${impacts.join(', ') || '-'} → ${assets.join(', ') || '-'}`
  );
  lines.push('');

  // Market impact table
  if (assets.length > 0) {
    lines.push('## 市场影响');
    lines.push('');
    lines.push('| 标的 | 方向 | 影响程度 |');
    lines.push('|---|---|---|');
    for (const node of data.nodes.filter(n => n.type === 'asset')) {
      const sentiment = node.sentiment === 'positive' ? '看涨' :
        node.sentiment === 'negative' ? '看跌' : '中性';
      // Find the edge weight pointing to this asset
      const edge = data.edges.find(e => e.target === node.id);
      const weight = edge?.weight || 'medium';
      const weightLabel = weight === 'critical' ? '极高' :
        weight === 'high' ? '高' : weight === 'medium' ? '中' : '低';
      lines.push(`| ${node.label} | ${sentiment} | ${weightLabel} |`);
    }
    lines.push('');
  }

  // AI Insight
  if (data.summary) {
    lines.push('## AI 洞察');
    lines.push('');
    lines.push(data.summary);
    lines.push('');
  }

  // Actions
  if (data.coreActions?.length) {
    lines.push('## 操作建议');
    lines.push('');
    for (const action of data.coreActions) {
      lines.push(`- ${action}`);
    }
    lines.push('');
  }

  // Polymarket
  if (matchedMarkets?.length) {
    lines.push('## 预测市场关联');
    lines.push('');
    for (const m of matchedMarkets) {
      const prob = Math.round((m.yes_probability ?? 0) * 100);
      lines.push(`- ${m.question} (${prob}%)`);
    }
    lines.push('');
  }

  // Scenarios
  if (data.scenarios?.length) {
    lines.push('## 场景判断');
    lines.push('');
    for (const s of data.scenarios) {
      const prob = Math.round(s.probability * 100);
      lines.push(`- **${s.name}** (${prob}%) — ${s.rationale}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by LiveBoard*');

  return lines.join('\n');
}

/**
 * Generate a plain-text version of the report.
 */
export function generatePlainText(report: ReportData): string {
  const { hotspot, timestamp, data, matchedMarkets } = report;
  const time = new Date(timestamp).toLocaleString('zh-CN', {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit',
  });

  const lines: string[] = [];
  lines.push('LiveBoard 分析报告');
  lines.push('='.repeat(40));
  lines.push('');
  lines.push(`事件: ${hotspot}`);
  lines.push(`分析时间: ${time}`);
  lines.push('');

  // Chain
  const hotspots = data.nodes.filter(n => n.type === 'hotspot').map(n => n.label);
  const variables = data.nodes.filter(n => n.type === 'variable').map(n => n.label);
  const impacts = data.nodes.filter(n => n.type === 'impact').map(n => n.label);
  const assets = data.nodes.filter(n => n.type === 'asset').map(n => n.label);

  lines.push('[传导链]');
  lines.push(
    `${hotspots.join(', ') || '-'} -> ${variables.join(', ') || '-'} -> ${impacts.join(', ') || '-'} -> ${assets.join(', ') || '-'}`
  );
  lines.push('');

  // Market impact
  if (assets.length > 0) {
    lines.push('[市场影响]');
    for (const node of data.nodes.filter(n => n.type === 'asset')) {
      const sentiment = node.sentiment === 'positive' ? '看涨' :
        node.sentiment === 'negative' ? '看跌' : '中性';
      const edge = data.edges.find(e => e.target === node.id);
      const weight = edge?.weight || 'medium';
      const weightLabel = weight === 'critical' ? '极高' :
        weight === 'high' ? '高' : weight === 'medium' ? '中' : '低';
      lines.push(`  ${node.label} | ${sentiment} | ${weightLabel}`);
    }
    lines.push('');
  }

  // Summary
  if (data.summary) {
    lines.push('[AI 洞察]');
    lines.push(data.summary);
    lines.push('');
  }

  // Actions
  if (data.coreActions?.length) {
    lines.push('[操作建议]');
    for (const a of data.coreActions) {
      lines.push(`  - ${a}`);
    }
    lines.push('');
  }

  // Polymarket
  if (matchedMarkets?.length) {
    lines.push('[预测市场关联]');
    for (const m of matchedMarkets) {
      const prob = Math.round((m.yes_probability ?? 0) * 100);
      lines.push(`  - ${m.question} (${prob}%)`);
    }
    lines.push('');
  }

  // Scenarios
  if (data.scenarios?.length) {
    lines.push('[场景判断]');
    for (const s of data.scenarios) {
      const prob = Math.round(s.probability * 100);
      lines.push(`  - ${s.name} (${prob}%) -- ${s.rationale}`);
    }
    lines.push('');
  }

  lines.push('-- Generated by LiveBoard --');

  return lines.join('\n');
}

/**
 * Copy text to clipboard with fallback.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    try {
      document.execCommand('copy');
      return true;
    } catch {
      return false;
    } finally {
      document.body.removeChild(textarea);
    }
  }
}
